// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	ad "barbz.dev/marketplace/internal/pkg/domain/ad"

	mock "github.com/stretchr/testify/mock"

	valueobject "barbz.dev/marketplace/pkg/valueobject"
)

// AdRepository is an autogenerated mock type for the AdRepository type
type AdRepository struct {
	mock.Mock
}

type AdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AdRepository) EXPECT() *AdRepository_Expecter {
	return &AdRepository_Expecter{mock: &_m.Mock}
}

// FindAdById provides a mock function with given fields: ctx, id
func (_m *AdRepository) FindAdById(ctx context.Context, id valueobject.AdId) (ad.Ad, error) {
	ret := _m.Called(ctx, id)

	var r0 ad.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.AdId) (ad.Ad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.AdId) ad.Ad); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(ad.Ad)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.AdId) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdRepository_FindAdById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAdById'
type AdRepository_FindAdById_Call struct {
	*mock.Call
}

// FindAdById is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.AdId
func (_e *AdRepository_Expecter) FindAdById(ctx interface{}, id interface{}) *AdRepository_FindAdById_Call {
	return &AdRepository_FindAdById_Call{Call: _e.mock.On("FindAdById", ctx, id)}
}

func (_c *AdRepository_FindAdById_Call) Run(run func(ctx context.Context, id valueobject.AdId)) *AdRepository_FindAdById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.AdId))
	})
	return _c
}

func (_c *AdRepository_FindAdById_Call) Return(_a0 ad.Ad, _a1 error) *AdRepository_FindAdById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdRepository_FindAdById_Call) RunAndReturn(run func(context.Context, valueobject.AdId) (ad.Ad, error)) *AdRepository_FindAdById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllAds provides a mock function with given fields: ctx
func (_m *AdRepository) FindAllAds(ctx context.Context) ([]ad.Ad, error) {
	ret := _m.Called(ctx)

	var r0 []ad.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]ad.Ad, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []ad.Ad); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ad.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdRepository_FindAllAds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllAds'
type AdRepository_FindAllAds_Call struct {
	*mock.Call
}

// FindAllAds is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AdRepository_Expecter) FindAllAds(ctx interface{}) *AdRepository_FindAllAds_Call {
	return &AdRepository_FindAllAds_Call{Call: _e.mock.On("FindAllAds", ctx)}
}

func (_c *AdRepository_FindAllAds_Call) Run(run func(ctx context.Context)) *AdRepository_FindAllAds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AdRepository_FindAllAds_Call) Return(adResponse []ad.Ad, err error) *AdRepository_FindAllAds_Call {
	_c.Call.Return(adResponse, err)
	return _c
}

func (_c *AdRepository_FindAllAds_Call) RunAndReturn(run func(context.Context) ([]ad.Ad, error)) *AdRepository_FindAllAds_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAd provides a mock function with given fields: ctx, _a1
func (_m *AdRepository) SaveAd(ctx context.Context, _a1 ad.Ad) (ad.Ad, error) {
	ret := _m.Called(ctx, _a1)

	var r0 ad.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ad.Ad) (ad.Ad, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ad.Ad) ad.Ad); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(ad.Ad)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ad.Ad) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdRepository_SaveAd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAd'
type AdRepository_SaveAd_Call struct {
	*mock.Call
}

// SaveAd is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 ad.Ad
func (_e *AdRepository_Expecter) SaveAd(ctx interface{}, _a1 interface{}) *AdRepository_SaveAd_Call {
	return &AdRepository_SaveAd_Call{Call: _e.mock.On("SaveAd", ctx, _a1)}
}

func (_c *AdRepository_SaveAd_Call) Run(run func(ctx context.Context, _a1 ad.Ad)) *AdRepository_SaveAd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ad.Ad))
	})
	return _c
}

func (_c *AdRepository_SaveAd_Call) Return(_a0 ad.Ad, _a1 error) *AdRepository_SaveAd_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdRepository_SaveAd_Call) RunAndReturn(run func(context.Context, ad.Ad) (ad.Ad, error)) *AdRepository_SaveAd_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAdRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdRepository creates a new instance of AdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdRepository(t mockConstructorTestingTNewAdRepository) *AdRepository {
	mock := &AdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
