name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install mockery
      working-directory: ./marketplace
      run: go get github.com/vektra/mockery/.../

    - name: Build
      working-directory: ./marketplace
      run: go build -v ./...

    - name: Generate mocks
      working-directory: ./marketplace
      run: go generate ./...

    - name: Unit test
      working-directory: ./marketplace
      run: make unit-test

    - name: Acceptance test
      working-directory: ./marketplace
      run: make acceptance-test

    - name: Contract test
      working-directory: ./marketplace
      run: make contract-test
