name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      working-directory: ./marketplace
      run: go build -v ./...

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Unit test
      working-directory: ./marketplace
      run: make -d unit-test

  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Acceptance test
      working-directory: ./marketplace
      run: make -d  acceptance-test

  contract-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install mockery
      working-directory: ./marketplace
      run: go install github.com/vektra/mockery/v2@v2.20.0

    - name: Contract test
      working-directory: ./marketplace
      run: make -d contract-test
